services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Security\AppCustomAuthenticator:
        autowire: true
        autoconfigure: true
        tags: ['security.authenticator']

    App\Repository\UserRepository:
        tags: ['doctrine.repository_service']

    App\Repository\PreguntaRepository:
        autowire: true
        autoconfigure: true

    App\Repository\RespuestaRepository:
        autowire: true
        autoconfigure: true